services:
  - type: web
    name: angular-app
    env: static
    staticPublishPath: dist/movie-system
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
